service: image-resizing-ruby

provider:
  name: aws
  runtime: ruby2.5
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'

functions:
  resize:
    handler: handler.call
    environment:
      BUCKET: resized-images-ruby
      REGION: eu-west-1
    events:
      - http:
          path: /{size}/{image}
          method: get

resources:
  Resources:
    ResizedImages:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: resized-images-ruby

plugins:
  - serverless-s3-local
  - serverless-offline
  - serverless-ruby-package

package:
  include:
    - handler.rb
    - lib/**
